/**
 * Neutralino payload injector — v3.0.0
 * Output: ~5 MB Neutralino project (vs ~350 MB Electron)
 * localStorage persists natively via WebView2 profile storage.
 */

import { cpSync, mkdirSync, writeFileSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

export function portFromSlug(slug) {
  let h = 0;
  for (const c of slug) h = Math.imul(h, 31) + c.charCodeAt(0) | 0;
  return 49152 + (Math.abs(h) % 16382);
}

function buildConfig({ appName, slug, port, version, hasIcon }) {
  return JSON.stringify({
    applicationId:   `com.artifact-to-pwa.${slug}`,
    version:         '1.0.0',
    defaultMode:     'window',
    port,
    documentRoot:    '/resources/',
    url:             '/',
    enableServer:    true,
    enableNativeAPI: true,
    tokenSecurity:   'one-time',
    logging:         { enabled: false, writeToLogFile: false },
    nativeBlockList: [],
    globalVariables: {},
    modes: {
      window: {
        title: appName, width: 1280, height: 800,
        minWidth: 400, minHeight: 300, resizable: true,
        exitProcessOnClose: true, enableInspector: false,
        ...(hasIcon ? { icon: '/resources/icons/appIcon.png' } : {}),
      },
    },
    cli: {
      binaryName: slug, resourcesPath: '/resources/',
      extensionsPath: '/extensions/', clientLibrary: '/resources/js/neutralino.js',
      binaryVersion: version, clientVersion: version,
    },
  }, null, 2);
}

function launchReadme(appName) {
  return [
    `${appName} \u2014 built by artifact-to-pwa`, '='.repeat(appName.length + 24), '',
    'HOW TO LAUNCH', '-------------',
    `Double-click: ${appName}.exe`, '',
    'REQUIREMENTS', '------------',
    'Requires Microsoft WebView2 (pre-installed on Windows 11 and',
    'Windows 10 updated after January 2023).', '',
    'If the app fails to open, download WebView2 (1.5 MB) from:',
    '  https://developer.microsoft.com/microsoft-edge/webview2/', '',
    'SMARTSCREEN WARNING', '-------------------',
    'If prompted: click "More info" \u2192 "Run anyway".',
    'This appears once per machine for unsigned apps.', '',
    'YOUR DATA', '---------',
    'App data is stored by Windows at:',
    `  %LOCALAPPDATA%\\com.artifact-to-pwa.APP_SLUG\\EBWebView\\`,
    '(Standard WebView2 profile \u2014 managed by Windows.)', '',
    'TO SHARE', '--------',
    'Zip the entire folder and send it.', '',
    '---',
    'Generated by artifact-to-pwa  https://github.com/Baaqar-007/artifact-to-pwa',
  ].join('\n');
}

export async function injectPayload({ binPath, clientLibPath, html, appName, slug, port, neutralinoVersion, outDir, iconPath, chalk }) {
  const resourcesDir = join(outDir, 'resources');
  const jsDir        = join(resourcesDir, 'js');
  mkdirSync(jsDir, { recursive: true });

  process.stdout.write(chalk.gray('  \u21b3 Copying runtime...'));
  const exeDest = join(outDir, `${appName}.exe`);
  cpSync(binPath, exeDest);
  console.log(' ' + chalk.green('done'));

  let hasIcon = false;
  if (iconPath) {
    process.stdout.write(chalk.gray('  \u21b3 Copying icon...'));
    try {
      const iconsDir = join(resourcesDir,'icons');
      mkdirSync(iconsDir,{recursive:true});
      cpSync(iconPath, join(iconsDir,'appIcon.png'));
      hasIcon = true;
      console.log(' ' + chalk.green('done'));
    } catch(err) { console.log(' ' + chalk.yellow('skipped') + chalk.gray(` (${err.message})`)); }
  }

  process.stdout.write(chalk.gray('  \u21b3 Patching exe...'));
  try {
    const { default: rcedit } = await import('rcedit');
    const opts = {
      'version-string': { FileDescription: appName, ProductName: appName, OriginalFilename: `${appName}.exe` },
      'file-version': '1.0.0.0', 'product-version': '1.0.0.0',
    };
    if (iconPath) {
      try {
        const { default: pngToIco } = await import('png-to-ico');
        const ico = await pngToIco(iconPath);
        const icoPath = join(outDir,'_icon.ico');
        writeFileSync(icoPath, ico);
        opts.icon = icoPath;
      } catch {}
    }
    await rcedit(exeDest, opts);
    console.log(' ' + chalk.green('done'));
  } catch(err) { console.log(' ' + chalk.yellow('skipped') + chalk.gray(` \u2014 ${err.message}`)); }

  writeFileSync(join(outDir,'neutralino.config.json'), buildConfig({appName,slug,port,version:neutralinoVersion,hasIcon}));
  console.log(chalk.green('  \u2713 ') + chalk.gray('neutralino.config.json'));

  cpSync(clientLibPath, join(jsDir,'neutralino.js'));
  console.log(chalk.green('  \u2713 ') + chalk.gray('resources/js/neutralino.js'));

  writeFileSync(join(resourcesDir,'index.html'), html, 'utf8');
  const check = readFileSync(join(resourcesDir,'index.html'),'utf8');
  if (!check.trim()) throw new Error('index.html written empty \u2014 possible disk issue.');
  console.log(chalk.green('  \u2713 ') + chalk.gray(`resources/index.html (${(check.length/1024).toFixed(0)} kB)`));

  writeFileSync(join(outDir,'README-Launch.txt'), launchReadme(appName));
  console.log(chalk.green('  \u2713 ') + chalk.gray('README-Launch.txt'));
}
