/**
 * Windows payload injector.
 *
 * Copies the prebuilt Electron shell, writes app resources into
 * resources/app/, renames electron.exe, and optionally swaps the icon.
 *
 * Output structure:
 *   <AppName>-windows/
 *   \u251c\u2500\u2500 <AppName>.exe
 *   \u251c\u2500\u2500 *.dll / *.pak  (Electron runtime)
 *   \u251c\u2500\u2500 resources/app/
 *   \u2502   \u251c\u2500\u2500 main.js
 *   \u2502   \u251c\u2500\u2500 preload.js
 *   \u2502   \u251c\u2500\u2500 package.json
 *   \u2502   \u2514\u2500\u2500 web/index.html
 *   \u2514\u2500\u2500 README-Launch.txt
 */

import { cpSync, mkdirSync, writeFileSync, readFileSync, copyFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname   = dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = join(__dirname, '..', 'template');

function launchReadme(appName) {
  return `${appName} \u2014 built by artifact-to-pwa\n${'='.repeat(appName.length + 24)}\n\nHOW TO LAUNCH (Windows)\n-----------------------\nThis app is unsigned. Windows SmartScreen may warn on first run.\n\n  1. Double-click ${appName}.exe\n  2. If you see "Windows protected your PC":\n       \u2192 Click "More info"\n       \u2192 Click "Run anyway"\n\nYou will only see this warning once per machine.\n\nTO SHARE THIS APP\n-----------------\nZip the entire "${appName}-windows" folder and send it.\n\nDATA & PRIVACY\n--------------\nAll app data is stored locally at:\n  %APPDATA%\\\\${appName}\\\\storage.json\n\n---\nGenerated by artifact-to-pwa  https://github.com/Baaqar-007/artifact-to-pwa\n`;
}

export async function injectPayload({ shellDir, html, appName, slug, outDir, iconPath, chalk }) {
  process.stdout.write(chalk.gray('  \u21b3 Copying shell...'));
  mkdirSync(outDir, { recursive: true });
  cpSync(shellDir, outDir, { recursive: true });
  console.log(' ' + chalk.green('done'));

  const appDir = join(outDir, 'resources', 'app');
  const webDir = join(appDir, 'web');
  mkdirSync(webDir, { recursive: true });

  writeFileSync(join(appDir, 'package.json'), JSON.stringify({ name: slug, version: '1.0.0', main: 'main.js' }, null, 2));
  copyFileSync(join(TEMPLATE_DIR, 'main.js'),    join(appDir, 'main.js'));
  copyFileSync(join(TEMPLATE_DIR, 'preload.js'), join(appDir, 'preload.js'));
  writeFileSync(join(webDir, 'index.html'), html, 'utf8');

  const verify = readFileSync(join(webDir, 'index.html'), 'utf8');
  if (!verify.trim()) throw new Error('index.html written but empty — possible disk issue.');
  console.log(chalk.green('  \u2713 ') + chalk.gray('resources/app/ created'));

  const exeSrc  = join(outDir, 'electron.exe');
  const exeDest = join(outDir, `${appName}.exe`);
  if (!existsSync(exeSrc)) throw new Error(`electron.exe not found in shell: ${outDir}`);
  cpSync(exeSrc, exeDest);

  const rceditOpts = {
    'version-string': { FileDescription: appName, ProductName: appName, OriginalFilename: `${appName}.exe` },
    'file-version': '1.0.0.0', 'product-version': '1.0.0.0',
  };

  if (iconPath) {
    process.stdout.write(chalk.gray('  \u21b3 Converting icon...'));
    try {
      const { default: pngToIco } = await import('png-to-ico');
      const icoBuffer = await pngToIco(iconPath);
      const icoPath   = join(outDir, '_icon.ico');
      writeFileSync(icoPath, icoBuffer);
      rceditOpts.icon = icoPath;
      console.log(' ' + chalk.green('done'));
    } catch (err) {
      console.log(' ' + chalk.yellow('skipped') + chalk.gray(` (${err.message})`));
    }
  }

  process.stdout.write(chalk.gray('  \u21b3 Patching exe...'));
  try {
    const { default: rcedit } = await import('rcedit');
    await rcedit(exeDest, rceditOpts);
    console.log(' ' + chalk.green('done'));
  } catch (err) {
    console.log(' ' + chalk.yellow('skipped') + chalk.gray(` \u2014 rcedit: ${err.message}`));
  }

  try { (await import('fs')).unlinkSync(exeSrc); } catch {}

  writeFileSync(join(outDir, 'README-Launch.txt'), launchReadme(appName));
  console.log(chalk.green('  \u2713 ') + chalk.gray('README-Launch.txt written'));
}
