import { wrapCode } from './detect.js';

/**
 * Builds the main index.html.
 * In URL mode the artifact is embedded in a full-screen iframe.
 * In code mode the source is compiled/wrapped via detect.js.
 */
export function buildIndexHTML(config) {
  const { mode, code, url, appName, themeColor } = config;

  const headInjects = `
  <meta name="theme-color" content="${themeColor}">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta name="apple-mobile-web-app-title" content="${appName}">
  <link rel="apple-touch-icon" href="icon.svg">
  <link rel="manifest" href="manifest.json">`.trim();

  const swScript = `
<script>
  if ('serviceWorker' in navigator) {
    window.addEventListener('load', () =>
      navigator.serviceWorker.register('sw.js').catch(() => {})
    );
  }
</script>`.trim();

  if (mode === 'url') {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${appName}</title>
  ${headInjects}
  <style>
    *     { margin: 0; padding: 0; box-sizing: border-box; }
    html,
    body   { width: 100%; height: 100%; overflow: hidden; }
    iframe { width: 100%; height: 100%; border: none; display: block; }
  </style>
  ${swScript}
</head>
<body>
  <iframe
    src="${url}"
    allow="fullscreen; clipboard-write; clipboard-read"
    sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-modals"
  ></iframe>
</body>
</html>`;
  }

  return wrapCode(code, { appName, themeColor });
}

/**
 * Builds a Web App Manifest (manifest.json).
 */
export function buildManifest({ appName, shortName, description, themeColor, bgColor }) {
  const manifest = {
    name: appName,
    short_name: shortName || appName.slice(0, 12),
    description: description || '',
    start_url: './',
    scope: './',
    display: 'standalone',
    orientation: 'any',
    theme_color: themeColor,
    background_color: bgColor,
    icons: [
      {
        src: 'icon.svg',
        sizes: 'any',
        type: 'image/svg+xml',
        purpose: 'any maskable',
      },
    ],
  };
  return JSON.stringify(manifest, null, 2);
}

/**
 * Builds a network-first service worker with offline fallback.
 */
export function buildServiceWorker({ slug }) {
  const CACHE = `${slug}-v1`;
  return `// Service worker generated by artifact-to-pwa
const CACHE  = '${CACHE}';
const ASSETS = ['./', './index.html', './manifest.json', './icon.svg'];

// ── Install: pre-cache core assets ───────────────────────────────────────────
self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE)
      .then(cache => cache.addAll(ASSETS))
      .catch(() => { /* non-fatal if assets are missing at install time */ })
  );
  self.skipWaiting();
});

// ── Activate: remove stale caches ────────────────────────────────────────────
self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(
        keys
          .filter(key => key !== CACHE)
          .map(key => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

// ── Fetch: network-first, cache fallback ─────────────────────────────────────
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;

  event.respondWith(
    fetch(event.request)
      .then(response => {
        // Cache a copy of successful responses
        if (response.ok) {
          const clone = response.clone();
          caches.open(CACHE).then(cache => cache.put(event.request, clone));
        }
        return response;
      })
      .catch(() => caches.match(event.request))
  );
});
`;
}

/**
 * Builds a README.md for the generated PWA project.
 */
export function buildReadme({ appName, slug }) {
  return `# ${appName}

> Generated by [artifact-to-pwa](https://github.com/yourusername/artifact-to-pwa)

## Install

### Quickest (local)
\`\`\`bash
npx serve .
\`\`\`
Open the printed URL in Chrome/Edge → click the **Install** icon in the address bar.

### Android (Chrome)
Deploy to any static host, then visit on Android → ⋮ → **Add to Home Screen**.

### iPhone / iPad (Safari)
Deploy → open in Safari → **Share** → **Add to Home Screen**.

## One-click deploy

| Host | Steps |
|------|-------|
| **Netlify** | Drag this folder to [netlify.com/drop](https://netlify.com/drop) |
| **Vercel** | \`npx vercel .\` |
| **GitHub Pages** | Push to a repo, enable Pages in Settings |

## Files

| File | Purpose |
|------|---------|
| \`index.html\` | App entry point |
| \`manifest.json\` | PWA metadata (name, icons, colors) |
| \`sw.js\` | Service worker — enables offline use |
| \`icon.svg\` | App icon (scales to any size) |
`;
}
